name: Lost Ark Price Auto-Update
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🟢 Installation Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Installation des dépendances
        run: |
          npm install
          npx playwright install chromium --with-deps

      - name: 🕷️ Lancement du Scraper
        run: node server.js

      - name: 📤 Envoi des prix
        run: |
          git config --global user.name 'Abidos-Bot'
          git config --global user.email 'bot@abidos.com'
          git add data.json
          git commit -m "⚡ MAJ Prix Automatique" || exit 0
          git push
